### ISSUE TITLE
Serverless nested routes not being persisted

### ISSUE THREAD

**Issue by smorris1709** [gurkerl83/next-i18next-serverless#2]
Not sure if this is an implementation issue or whether its something to do with the serverless env

But when I got this setup up and running, but when I go to a nested dynamic route the language resets to default again.

**Comment by gurkerl83** [comment]
The following repo uses next-i18next-serverless, but here I am not using dynamic routes. https://github.com/project-millipede/millipede-docs. Did it work using the standard next-i18next package, but I guess then you can not utilize the latest Next features. Maybe there is a bug how we look for languages in the create-config file.

**Comment by smorris1709** [comment]
I have followed your implementation for this and got it working so far but then thats the issue I face where when I go to a dynamic route ie subjects/[slug].js thats when it would reset the default language. 

my _app.js is only using a layout wrapper not really using any state but local state as its all just api calls and displaying data so pretty simple setup

**Comment by gurkerl83** [comment]
You have also integrated the middleware in _document as described?

https://github.com/project-millipede/millipede-docs/blob/18406bfe8e8bcdaff0197ce6b5a10a2a15aafc16/pages/_document.tsx#L73

**Comment by smorris1709** [comment]
Yeah done that.

**Comment by gurkerl83** [comment]
Can you share the link you received from Now, where the app was deployed to, or a minimal repository so I can have a look.

**Comment by smorris1709** [comment]
Yeah its this I think im on my mobile now so if its not quite the right one will update in the morning 

https://school-toolkit-website.now.sh/

**Comment by gurkerl83** [comment]
The application already seems a bit large for debugging the problem. Maybe you can use the example from https://github.com/gurkerl83/next-i18next-serverless/tree/temporal-save and add a simple dynamic route. For now I have really no cycles back to help.

**Comment by smorris1709** [comment]
Ah okay, no worries thank you for having a look anyway! Really appreciate it.

I will have a look and see what I can do on that I didn't see that example there is that a new thing you have just done?

**Comment by gurkerl83** [comment]
No its on the temporal-safe feature and works with serverless deployment of Now, just check the feature our declare a dynamic page and see what happens. Thx.

**Comment by smorris1709** [comment]
Right i've set up nested routes so if you check the repo out here 
https://github.com/smorris1709/next-i18next-serverless-sample

Url for the app on now is here
https://next-i18next-serverless-sample-mz3zm3zmp.now.sh/


you can see that when you change locale and then go to the subject page it resets back to english.

**Comment by gurkerl83** [comment]
Nice, I will look into it, thx

**Comment by smorris1709** [comment]
i think if i remember rightly it does the same on the express middleware example too. if that helps you in anyway.

**Comment by gurkerl83** [comment]
Hi, I just tried the test repo you provided. I think dynamic routes are working. For those to work, you have to modify the navigation component with the following. Maybe I do not fully understand the use case of dynamic routes just yet, but the following works for me.

```
<Link href='/subjects/[subject]' as={`/subjects/${1}`}>
   <button type='button'>{t('to-subject')}</button>
</Link>

or

const subjectIds = ['id1', 'id2', 'id3'];

{subjectIds.map(id => (
   <Link href='/subjects/[subject]' as={`/subjects/${id}`}>
   <button type='button'>{`${t('to-subject')} ${id}`}</button>
   </Link>
))}
```

Here is the code and the deployed version
https://github.com/gurkerl83/next-i18next-serverless-sample/tree/Dynamic-Routes
https://millipede-docs-simple.gurkerl83.now.sh/
